### ISSUE TITLE
Submit to ICT Open?

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#103]
Deadline for abstract submission is 28 Jan, so within the sprint duration, though not on the sprint topic.

- **Do we submit (no research results actually)?** 
- What type of[ abstract shall we submit](https://www.ictopen.nl/submit-an-abstract/)- demo, oral or poster?
- What is the tittle?
- Who will present it- what is the order of authors?

**Comment by elboyran** [comment]
At the discussion on 17.01 we decided to submit a (possibly) interactive demo. Elena will prepare abstract and also contact Communications about participation and budget.

**Comment by elboyran** [comment]
Here is the abstract summary (max 250 words, currently all limit is used):


> Modern scientific challenges are often tackled with (Deep) Neural Networks (DNN). Despite their high predictive accuracy, DNNs lack inherent explainability. Many scientists from different scientific domains do not harvest DNNs power because of lack of trust and understanding of their working. Meanwhile, the eXplainable AI (XAI) research offers some post-hoc (after training) interpretability methods that provide insight into the DNN reasoning by quantifying the relevance of individual features (image pixels, words in text, etc.) with respect to the prediction. These relevance heatmaps indicate how the network has reached its decision directly in the input modality (images, text, speech etc.) of the scientific data. Representing visually the captured knowledge by the AI system can become a source of scientific insights. There are many Open Source Software (OSS) implementations of these methods, alas, supporting a single DNN format, while standards like Open Neural Network eXchange (ONNX) exist. The libraries are known mostly by the AI experts. For the adoption by the wide scientific community understanding of the XAI methods and well-documented and standardized OSS are needed. In the Deep Insight And Neural Network Analysis (DIANNA) project we have selected the best XAI methods in the context of scientific usage evaluated by extensive objective criteria. The DIANNA library is a well-documented OSS implementation of these methods, supporting the ONNX standard and comes along with few benchmark datasets for intuitive understanding and methods comparison. Come to meet and see DIANNA on the benchmarks or bring along your data and model to get new insights! 


**Please edit if needed by 4p.m. today**

Screenshots from the submission page, **let me know if I should change something by 4p.m. today**:

<img width="1305" alt="ICTOpenDraft1" src="https://user-images.githubusercontent.com/3244249/151526442-fc31d95e-bca2-4d4b-9afc-e0ca60b4fbdf.png">
<img width="1160" alt="ICTOpenDraft2" src="https://user-images.githubusercontent.com/3244249/151526443-cbac84ee-ec00-412c-9678-4a98ac9c338f.png">
<img width="1160" alt="ICTOpenDraft3" src="https://user-images.githubusercontent.com/3244249/151526446-2332f837-7c2c-4c2f-830b-9bc9cee45c2f.png">
<img width="1163" alt="ICTOpenDraft4" src="https://user-images.githubusercontent.com/3244249/151526437-08aa7782-6268-4c03-8c64-9b0f437654d5.png">
<img width="1186" alt="ICTOpenDraft5" src="https://user-images.githubusercontent.com/3244249/151526441-70892b77-9aae-4154-9aa4-c08895907656.png">

**Comment by geek-yang** [comment]
@elboyran Looks awesome! Indeed, just find that some formulations in the abstract sound quite familiar to me (guess they appear somewhere in the proposal as well ^_^ ). It is very clear and I didn't spot any typo. I don't have anything to add and I think it is ready to submit.

**Comment by egpbos** [comment]
I would make the title a bit more inviting and descriptive, something like:

"Come meet DIANNA: explainable AI for your research projects"

Abstract looks good! Here some suggested edits for language (**bold** additions, ~strikethrough~ removals, _italic_ with question below):

Modern scientific challenges are often tackled with (Deep) Neural Networks (DNN). Despite their high predictive accuracy, DNNs lack inherent explainability. **This leads m**any scientists ~from different scientific domains do not harvest~ **to avoid** DNNs ~power~ because of lack of trust and understanding of their working. Meanwhile, ~the~ eXplainable AI (XAI) research offers some post-hoc (after training) interpretability methods that provide insight into ~the~ DNN reasoning by quantifying the relevance of individual features (image pixels, words in text, etc.) with respect to the prediction. These relevance heatmaps indicate how the network has reached its decision directly in the input modality (images, text, speech etc.) of the scientific data. _Representing visually the captured knowledge by the AI system can become a source of scientific insights_. There are many Open Source Software (OSS) implementations of these methods, alas, supporting a single DNN format, while standards like Open Neural Network eXchange (ONNX) exist. The**se** libraries are known mostly by ~the~ AI experts. For ~the~ adoption by the wide scientific community understanding of the XAI methods and well-documented and standardized OSS are needed. In the Deep Insight And Neural Network Analysis (DIANNA) project we have selected the best XAI methods in the context of scientific usage evaluated by extensive objective criteria. The DIANNA library is a well-documented OSS implementation of these methods, supporting the ONNX standard and comes along with ~few~ benchmark datasets for intuitive understanding and methods comparison. Come ~to~ meet and see DIANNA **in action** on the benchmarks or bring along your **own** data and model to get new insights!

_Representing visually..._: what do you want to say with this sentence exactly?

**Comment by elboyran** [comment]
> @elboyran Looks awesome! Indeed, just find that some formulations in the abstract sound quite familiar to me (guess they appear somewhere in the proposal as well ^_^ ). It is very clear and I didn't spot any typo. I don't have anything to add and I think it is ready to submit.

Yes, it's a copy & paste & edit from the proposal ;-)

**Comment by elboyran** [comment]
New draft:

Modern scientific challenges are often tackled with (Deep) Neural Networks (DNN). Despite their high predictive accuracy, DNNs lack inherent explainability. Therefore, many scientists avoid DNNs  because of lack of trust and understanding of their working. Meanwhile,  eXplainable AI (XAI) research offers some post-hoc (after training) interpretability methods that provide insight into  DNN reasoning by quantifying the relevance of individual features (image pixels, words in text, etc.) with respect to the prediction. These relevance heatmaps indicate how the network has reached its decision directly in the input modality (images, text, speech etc.) of the scientific data. Representing visually the captured knowledge by an AI model can become a source of scientific insights. There are many Open Source Software (OSS) implementations of these methods, alas, supporting a single DNN format, while standards like Open Neural Network eXchange (ONNX) exist. These libraries are known mostly by  AI experts. For  adoption by the wide scientific community understanding of the XAI methods and well-documented and standardized OSS are needed. In the Deep Insight And Neural Network Analysis (DIANNA) project we have selected the best XAI methods in the context of scientific usage evaluated by extensive objective criteria. The DIANNA library is a well-documented OSS implementation of these methods, supporting the ONNX standard and comes along with  benchmark datasets for intuitive understanding and methods comparison. Come  meet and see DIANNA in action on the benchmarks or bring along your own data and model to get new insights!

**Comment by elboyran** [comment]
Submitted.
