### ISSUE TITLE
Fix for installation on macbooks with M1 chips

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#200]
We have 2 reported cases of failure to install DIANNA on new macbooks with M1 chips. Apparently installation of Tensorflow is a problem on machines with these chips. One of our users with such a machine is our colleague Giulia so we can experiment with her machine to find a workable solution.
See for example: https://towardsdatascience.com/installing-tensorflow-on-the-m1-mac-410bb36b776
Or: https://towardsdatascience.com/installing-tensorflow-on-the-m1-mac-410bb36b776

**Comment by gcroci2** [comment]
Here I am, I have a Macbook Pro with chip M1 Pro and OS Monterey. I first installed Homebrew, XCode tools and MiniForge (which runs on all M1 chips) instead of Miniconda/Anaconda.

- First I followed the tutorial mentioned by @cwmeijer [https://towardsdatascience.com/installing-tensorflow-on-the-m1-mac-410bb36b776](https://towardsdatascience.com/installing-tensorflow-on-the-m1-mac-410bb36b776) (same [here](https://github.com/apple/tensorflow_macos/issues/153)).

  But when I copy the links to install **TensorFlow** and **TensorFlow Addons** in my conda evironment: 
  ```
  pip install --upgrade --force --no-dependencies https://github.com/apple/tensorflow_macos/releases/download/v0.1alpha3/tensorflow_addons_macos-0.1a3-cp38-cp38-macosx_11_0_arm64.whl https://github.com/apple/tensorflow_macos/releases/download/v0.1alpha3/tensorflow_macos-0.1a3-cp38-cp38-macosx_11_0_arm64.whl
  ```
  this is what I get:
  ```
  ERROR: tensorflow_addons_macos-0.1a3-cp38-cp38-macosx_11_0_arm64.whl is not a supported wheel on this platform.
  ```

  So an error for the first wheel (**TensorFlow Addons**) and no TensorFlow installation at all.

- Then I followed this most recent tutorial [https://betterdatascience.com/install-tensorflow-2-7-on-macbook-pro-m1-pro/](https://betterdatascience.com/install-tensorflow-2-7-on-macbook-pro-m1-pro/). What changes here is that python version for the environment is 3.9 (in the first tutorial is 3.8), and some **TensorFlow** dependencies from Apple are installed. Then with 
  ```
  python -m pip install tensorflow-macos
  ```
  
  **TensorFlow** (macos) is installed. Unfortunately, **TensorFlow Addons** is not, and it is needed as well for DIANNA.

_Additional notes_

I tried the procedure of the second tutorial in the environment with python 3.8 as well, and it gave me
```
ERROR: Could not find a version that satisfies the requirement tensorflow-macos (from versions: none)
ERROR: No matching distribution found for tensorflow-macos
```
So maybe with python 3.9 issues (with at least TensorFlow, not sure from which side) have been solved. *But* the official apple developer [website](https://developer.apple.com/metal/tensorflow-plugin/) states that both python versions 3.8 and 3.9 should be supported, so I am pretty confused.
