### ISSUE TITLE
Improve explanation results in the tutorial notebooks of LIME images

### ISSUE THREAD

**Issue by gcroci2** [dianna-ai/dianna#208]
Results from lime_images.ipynb:

<img width="261" alt="Screenshot 2022-02-08 at 13 07 48" src="https://user-images.githubusercontent.com/55382553/152984075-d4967847-d0e1-4f87-a267-63ee083dc3ff.png">

The results are better than previous ones, but still not satisfactory. The results were obtained by setting `num_features` of `dianna.explain_image` to 3, and it's not clear why only with this number it works better.

**Comment by egpbos** [comment]
I've also played around with this a bit and am starting to suspect that the model may not be an ideal match for the explainers we use.

First clue: RISE also gives poor results with the leaf model:
<img width="736" alt="afbeelding" src="https://user-images.githubusercontent.com/6146598/158882729-f281463d-866d-47e9-89ad-37575e4877d8.png">

Second clue: when using ImageNet instead of the leaf model, we get something that looks a lot more sensible, both with RISE:
<img width="736" alt="afbeelding" src="https://user-images.githubusercontent.com/6146598/158882822-28beb815-f1de-4691-992c-3799c9deecbc.png">

...and with LIME:
<img width="326" alt="afbeelding" src="https://user-images.githubusercontent.com/6146598/158882863-ae7d917b-dda9-4c27-841f-f741b1bd6fd8.png">

One hypothesis: the leaf model does not work so well with these image classification methods, because the task is subtly different from what these explainers are used to? The task with classification is typically to say what the image contains, right? But in the leaf case, what is the model trained on? If it always contains leafs (just of different types) then the leaf itself will typically not be the most discerning part of the image, but more things like edges and perhaps these explainers are just not so good with that.

**Comment by elboyran** [comment]
Will not work on this.
