### ISSUE TITLE
copy author list

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#232]
copy from readme / zenodo

**Comment by gcroci2** [comment]
Copied (see https://hackmd.io/@gcroci2/BywaTzTJc/edit). In the same section of the author list (between `---`) we need to put a date (I think the submission date) of course when we know. 

I am not sure if I should add myself in the author list, since I'm helping right at the end of the project, and everything is pretty much done. Feel free to share your thoughts on this :)

**Comment by elboyran** [comment]
Hi, the link does not work for me :-( Do I have to do first something on hackmd? 
I am also wondering about the author's list order. (It should be longer than the one in Zenodo, I think ;-)) For example if I should be the first or the last ;-) If we should add also Damian from SURF as co-PI in proposal, but in fact Mattiue joining us and doing some work?
Otherwise I propose the following order: (myself?), Chris, Leon, Yang, Patrick, Guilia, Mattiue, (Damian), (myself?)

**Comment by gcroci2** [comment]
> Hi, the link does not work for me :-( Do I have to do first something on hackmd? I am also wondering about the author's list order. (It should be longer than the one in Zenodo, I think ;-)) For example if I should be the first or the last ;-) If we should add also Damian from SURF as co-PI in proposal, but in fact Mattiue joining us and doing some work? Otherwise I propose the following order: (myself?), Chris, Leon, Yang, Patrick, Guilia, Mattiue, (Damian), (myself?)

Now at least @elboyran, @cwmeijer, @geek-yang and I should have access (text me if this is not true)

**Comment by elboyran** [comment]
@gcroci2 should we be seeing the author's list in HackMd? I don't see such a section there.

**Comment by gcroci2** [comment]
> @gcroci2 should we be seeing the author's list in HackMd? I don't see such a section there.

Yes it's in the section between `---` (title, tags, authors, affiliations, date, bibliography). It does not appear in the preview, but I think that when the .md file is compiled the right format will appear on the pdf. Of course we can try that when we'll merge the paper with the main branch.
