### ISSUE TITLE
Write draft blog post about XAI method selection

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#234]

**Comment by elboyran** [comment]
Describe the work we did in the dianna-exploration repo on the selection of initial XAI methods, selection criteria and final subset of XAI methods.

**Comment by elboyran** [comment]
The follwoing documents are relevant:
[List initial evaluation criteria](https://nlesc.sharepoint.com/:w:/s/DIANNA/ET9V1TVTpu1Cgww1sKhJ4IQBK__JSQ7XQ_u1VGkuryEnwg)
[Initial list XAI methods](https://nlesc.sharepoint.com/:w:/s/DIANNA/EVofzQCKJr9Bg5YUbyolAQgBevAtHxgxoTYx01CXFUqYmw)
[Selection XAI methos by criteria](https://nlesc.sharepoint.com/:w:/s/DIANNA/ET7gE4Wd-jlCq_rm0qjvJ9MBF-38sLKVaEWtMskUPJPiKw)

**Comment by elboyran** [comment]
Shall we use Medium from the start?

**Comment by elboyran** [comment]
Blogging
Last edited: 1/19
Submitting a blog
Anyone who wants to write a blog can compose a draft in [Medium](https://medium.com/@eScienceCenter). Please also submit a link to the draft in the [Submissions channel](https://teams.microsoft.com/l/channel/19%3a7e17997debe44e0e83812b0d6bd6b9b7%40thread.tacv2/Submissions?groupId=395332da-bfeb-457e-8640-9ba75968dbac&tenantId=aa3aeacc-6307-42b2-ac05-787dd5c32574). With questions about Medium, please contact Pablo R., Lieke, or Veronica. 

Reviewing blog posts
Anyone who’s a member of Blogging is allowed to review submissions. The editorial team will check if the blog has been looked over by others after a week. If it hasn’t, they may ask members of the blogging team for input on the submitted blog.

Publication
After review, the editorial team will schedule the publication in the posts queue, tune up the blog settings such as SEO title, tags, and license. If for some reason you would like everything to be faster, or to publish at a given date, please write to the Editorial team: Veronica Pang, Pablo Rodriguez-Sanchez or Lieke de Boer.

Writing hours

 
We’ve established that a single blog may take up to 13 hours to be written and reviewed. You can write your hours on project code 00020211 Dissemination and Community, hour type 00172 DC Online Resources. When logging your hours in Exact, it is helpful if you mention “blog” in the comment field.


Medium and corporate website
We are in the process of migrating our blogs to our own website instead of Medium to help drive traffic back to the new, shiny website. We will be sure to share updates as they become available.
Editorial team
Besides ensuring timely publication, the editorial team will keep their ears open in stand-ups and colloquia, and see if there are opportunities for people to write blog posts about some of the many amazing things that are happening at the Center. No one will be forced, everyone will be encouraged.

The editorial team now includes colleagues who were appointed for their relevant roles and experience (1 Communications advisor (Veronica), 1 Community Manager (Lieke) and 1 RSE with extensive blogging experience (Pablo R.)). However, we’d like to be an inclusive and dynamic group, so if you are interested in being a part of the editorial team, let one of us know.

**Comment by elboyran** [comment]
So, lets use these blogging hours ;-)

**Comment by elboyran** [comment]
Here is the [draft link](https://medium.com/@e.ranguelova/how-to-find-your-ai-explainer-dbb1ac608009).
Plan to use a ["Journey" style story-line](https://nlesc.sharepoint.com/qi/PublishingImages/SitePages/Communication/Storylines.pdf)

**Comment by geek-yang** [comment]
Here is the [draft](https://medium.com/@git-yang/select-explainable-ai-xai-methods-to-decrypt-your-blackbox-707a7271c79) I'm working on, which will contributes to the second half of the blog.

**Comment by elboyran** [comment]
Finished with drafting my half. Link in the comment above.

**Comment by elboyran** [comment]
I merged them, but the links to the tables do not work :-(

In @geek-yang 's blog they are horizontally scrollable, but not in the merged version when I simply paste the links.

Is it because it's @geek-yang gist account?

**Comment by cwmeijer** [comment]
See https://blog.esciencecenter.nl/using-c-in-a-web-app-with-webassembly-efd78c08469 for an example of how we handled authorship with the GT then.

**Comment by elboyran** [comment]
If anyone (e.g. @cwmeijer , @gcroci2) has time (see the blogging hours budget above for reporting the hours), please, leave comments on the blog. 
I plan to share the draft link with the Blogging team soon (say by Friday, 4th of March)

**Comment by cwmeijer** [comment]
I did a review of the blog post. Great work! 🥇 I left many comments and suggestions. I like the text a lot already so please keep that in mind that while reading my comments :-)

**Comment by cwmeijer** [comment]
@geek-yang and @elboyran, I left my comments as 'private notes'. My interpretation of it was that only the author of the blog could read them, but after discussing it with @gcroci2, it might very well mean that even the author of the blog cannot see them and I can only see them myself... Not super useful. We haven't figured out a way to actually share comments it seems.

**Comment by PabRod** [comment]
Hi everyone! 

I'll need the help of @elboyran. Please, add your publication to the Netherlands eScience Center blog.

You can do this by opening your draft, and clicking on the `...` button on the top right.

**Comment by elboyran** [comment]
Hi @PabRod , I will very soon (tomorrow or even today if I maange). 
I'd like to address Chis's comments first (@cwmeijer @geek-yang , @gcroci2, I can see them, thanks!).

**Comment by gcroci2** [comment]
I left very few private notes on the draft @elboyran. Great post!

**Comment by PabRod** [comment]
Hi @elboyran, and thanks.

I still need you to add it to our publication, as described [here](https://github.com/dianna-ai/dianna/issues/234#issuecomment-1057842160). I can submit it to the submissions channel for you after it is added.

**Comment by PabRod** [comment]
@elboyran I think you have to submit it, indeed. I didn't receive anything.

**Comment by elboyran** [comment]
@PabRod, now I Submitted.
