### ISSUE TITLE
Create issues for addressing JOSS reviews

### ISSUE THREAD

**Issue by cpranav93** [dianna-ai/dianna#367]

**Comment by cwmeijer** [comment]
Address the [JOSS reviews](https://github.com/openjournals/joss-reviews/issues/4493).
Also see #354.

**Comment by cwmeijer** [comment]
Blocked because we are waiting for the last reviewer to respond.

**Comment by cwmeijer** [comment]
No longer blocked. Also, I created the final issue, #394, that we need to address (I think).

**Comment by elboyran** [comment]
> No longer blocked. Also, I created the final issue, #394, that we need to address (I think). I think the current one should be closed. Do you agree @elboyran ?

Yes.

**Comment by elboyran** [comment]
@cwmeijer , @loostrum , can you, please, address the[ latest requests](https://github.com/openjournals/joss-reviews/issues/4493) by the JOSS editor?
Especially I do not know how can we change our permanent Zenodo record of the releases to match the authors of the paper and if that's possible at all, if we want to do that (SURF people and our PM contributed to one, but not to the other) and do I understand the second point of the editor in the first place? Is it about the filename only containing the authors? What us a DPI? Maybe this release could be then on FigShare? I guess on late September one is not enough because does not contain the latest paper changes.

**Comment by cwmeijer** [comment]
I'm guessing DPI is a typo. He means DOI. I can have a look, but especially concerning decisions about authors and such, I would like to do that together.
