### ISSUE TITLE
Add Leafsnap30 to DLHub

### ISSUE THREAD

**Issue by cpranav93** [dianna-ai/dianna#368]
Publish our [LefShap30 model(s)](https://zenodo.org/record/5907196) to[ DLHub](https://www.dlhub.org/).

**Comment by elboyran** [comment]
Turned out to be more work than I expected, see the [docs](https://dlhub-sdk.readthedocs.io/en/latest/index.html). Also, it seems it [does not support ONNX](https://dlhub-sdk.readthedocs.io/en/latest/servable-types.html).
 I am not sure which platform is more used DLHub or ONNX model zoo. Probably the former more by scientists, the latter by DL researchers? We want to support scientists, but also ONNX,...

1. Shall we publish only the PyTorch model to DLHub? or
2. Change the issue/deliverable to Add LeafSnap30 to [ONNX model zoo](https://github.com/onnx/models), see [how to contribute](https://github.com/onnx/models#contributions)?

Anyone interested to looking into the above dilemmas?
@loostrum. @cwmeijer, @cpranav93?

**Comment by cpranav93** [comment]
ONNX model zoo is the prefered option as it can connect with the DIANNA PR with ONNX in the future.
