### ISSUE TITLE
Investigate if LimeSegment's author welcome contributions 

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna#369]
Lime Segment (https://github.com/TortySivill/LIMESegment). 
For DIANNA would be nice if we can make it pip-installable. 
See conclusions of issue #358.

**Comment by elboyran** [comment]
[Torty Sivill](https://www.turing.ac.uk/people/doctoral-students/torty-sivill)

**Comment by loostrum** [comment]
So the conclusion of earlier issues is that we want to implement LIMESegment? Issue #358 seems to discuss this, but I don't see a clear conclusion there and the issue is closed.
I wanted to suggest that we could always just make it pip installable in a fork and use that, but I see that their repo has no license so we can't unless the author responds, so let's hope they do!

**Comment by elboyran** [comment]
@loostrum indeed, we need a clear conclusion as that was one of our main sprint goals. 
I opened the issue assuming that, but cannot find the clear conclusion.
Related to #358 and #366. 
@geek-yang and @cpranav93, given your research are we going for LIMESegment in DIANNA?

**Comment by cwmeijer** [comment]
We are probably going with Lime-for-TS. See #366.
