### ISSUE TITLE
Create release with matching authors and share on Zenodo for JOSS

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#397]
Elena wrote (in issue #367):
@cwmeijer and/or @loostrum , can you, please, address thehttps://github.com/openjournals/joss-reviews/issues/4493 by the JOSS editor?
Especially I do not know how can we change our permanent Zenodo record of the releases to match the authors of the paper and if that's possible at all, if we want to do that (SURF people and our PM contributed to one, but not to the other) and do I understand the second point of the editor in the first place? Is it about the filename only containing the authors? What us a DPI? Maybe this release could be then on FigShare? I guess on late September one is not enough because does not contain the latest paper changes.

**Comment by cwmeijer** [comment]
I'm guessing DPI is a typo. He means DOI. I can have a look, but especially concerning decisions about authors and such, I would like to do that together.

**Comment by loostrum** [comment]
@elboyran It would be possible indeed. We could consider creating a JOSS branch and keeping that indefinitely, as an easy way to browse through the code as it was at the time of the paper. If we think that's useful of course.

**Comment by elboyran** [comment]
@loostrum yes, lets make a branch and proceed if all authors agree with the proposal.

**Comment by egpbos** [comment]
I would say: whatever is the JOSS requirement, fulfill it with the least possible effort.

Btw, if I understand [the cited description here correctly](https://github.com/openjournals/joss-reviews/issues/4493#issuecomment-1320251504), I think Rena would be an edge case, since I don't think she did any "active project direction". It also states that the co-authors all should "agree to be accountable for all aspects of the work". I would say that means that you should really have some knowledge about the code, not just have given some input/feedback in some meetings. In fact, I'm wondering whether even Mathieu from SURF would qualify. He was our prime user and he should probably be mentioned explicitly in the acknowledgements, but he did not co-develop and I would guess he wouldn't like to be held accountable for the code. So, my strict interpretation would be that these authors wouldn't have qualified for this paper. However, I see they are already on the paper draft, so indeed, I would just add them to the software release as well to get the two in sync.

By the way, after the JOSS paper is published, how will we ask people to cite DIANNA? By the most recent software release or the JOSS paper? The most recent release would include all the contributors up to that point as co-authors, which I think is most fair. It's a bit of a shame though that the JOSS paper would not get cited a lot then, although I personally don't mind that much.

**Comment by elboyran** [comment]
Part of a comment from @cwmeijer on Teams: 

> I think the following might be acceptable (my interpretation of the approach proposed by Elena I guess):

> - Branch a release from the date we submitted the paper, and copy our paper into that branch and release that listing all paper authors as software authors. Downsides: It will require a bit of work and some GIT wizardry (merge cherry picked commits maybe?). We would include a group of people to our author list that haven't contributed anything (significant) and make them accountable for the code as well.

**Comment by geek-yang** [comment]
> @cwmeijer , @loostrum is it possible to make a single "JOSS release" with all paper's authors to share on Zenodo and then as of next releases to come back to our current software author's list?
> 
> Just checked: given the [history of our releases](https://zenodo.org/search?page=1&size=20&q=conceptrecid:%225592606%22&sort=-version&all_versions=True), it seems more than possible. @geek-yang, @cwmeijer, @loostrum, @egpbos, @gcroci2 do you agree with _adding_ Rena and the SURF people to such a release? 

I'm fine with it. and I agree with @egpbos about his concerns about authorship and citation. Indeed I have similar thoughts and it is nice that he summarizes this perfectly 👍!

**Comment by elboyran** [comment]
Blocked by #405 . Blocking #402 .

**Comment by cwmeijer** [comment]
I created a branch today from version [v0.4.1](https://github.com/dianna-ai/dianna/releases/tag/v0.4.1) which has as the first line of its description "This is the version at the time of our JOSS paper submission." After some commits and reverting something I messed up my local branch. I'll try again tomorrow. I haven't pushed anything yet.

**Comment by elboyran** [comment]
Any idea why is in not shown in [Zenodo](https://zenodo.org/record/7116103)?

**Comment by elboyran** [comment]
Sorry guys @cwmeijer, @loostrum , can you, please, check the editor's comments and maybe edit the release/Zenodo entry? I don't have any time tomorrow and on Monday.

          @elboyran We are close. Thanks for your patience. Can you please change the title on Zenodo to DIANNA: Deep Insight And Neural Network Analysis/ No need for a new release, you can just update the title.

_Originally posted by @diehlpk in https://github.com/openjournals/joss-reviews/issues/4493#issuecomment-1333986182_

        @elboyran Also the order of the authors is different.

_Originally posted by @diehlpk in https://github.com/openjournals/joss-reviews/issues/4493#issuecomment-1334011082_

**Comment by loostrum** [comment]
Zenodo takes a while to appear, that's why we didn't respond to the editor yet. I do have the edit button, I'll see if I can update the title and author order. We can't change the author order on the Github release btw, as that requires creating a new release. But I think that should be ok.

**Comment by loostrum** [comment]
Title and author order fixed, closing this when the editor agrees

**Comment by elboyran** [comment]
Thanks!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
