### ISSUE TITLE
Lime explanation crashes sometimes - special character related

### ISSUE THREAD

**Issue by laurasootes** [dianna-ai/dianna#437]
Relevances for Lime cannot always be calculated. The origin lies in that the created sentences are not always returned in equal length

**Comment by loostrum** [comment]
After quite some investigation we found that the issue lies in how LIME creates a list from the tokens. Take this example:
```'This movie is great !?'```
Tokenized, this would be:
```['This', 'movie', 'is', 'great', '!', '?']```
Now when LIME creates a list that represents the original input, it uses the same separators as the original, so like this:
```['This', ' ', 'movie', ' ', 'is', ' ', 'great', ' ', '!', '?']```

Let's say both special characters are masked and replaced by "UNKWORDZ" (the lime default).
The final sentences will then be
```This movie is great UNKWORDZUNKWORDZ```
The is no space between the two UNKWORDZ instances. When tokenizing this again, the resulting list is one token shorter than the original tokenized text. This mismatch in length of the sentence results in the "Cannot convert input to tensor" error. 

The proposed solution is to attempt to fix this in DIANNA by detecting special characters in the input and adding spaces around them, before forwarding the input to LIME. We have to be careful with the apostrophe: the input `let's` should be tokenized as `["let", "'s"]`.

A possibly incomplete list of special characters we might want to handel (taken from the vocab in the movie reviews model runner):
```
,
.
-
`
--
'
...
)
(
''
:
;
/
?
*
!
$
&
#
+
=
```

**Comment by loostrum** [comment]
I'll try implementing this in the SpacyTokenizer class that we have. That way it doesn't interfere with other users, that will probably user their own tokenizers.

**Comment by loostrum** [comment]
Unexpected situation: I tried adding a test to run with special chars, expecting it would fail and I could then fix it, but the test passed. Turns out that the movie review model runner as defined in tests/utils.py _does_ work, while the one in the dashboard/utilities.py does not work. I'll check the differences between the two and fix the one in the dashboard

**Comment by loostrum** [comment]
The difference is that the model runner in the dashboard runs all sentences through the model at once, while the one in tests does it one by one. Running it one by one hides the error rather than actually fix it.

In general it would make sense to run the sentences one by one so we can support running several different reviews of different length at the same time, but in reality we're always passing a single review. So I suggest we put the model runner that runs all sentences at the same time in both the dashboard and tests. That will break the test, which we can then fix by adding the special character support in the SpacyTokenizer class.
