### ISSUE TITLE
Add documentation/docstrings/examples of strategic masking based on wave function

### ISSUE THREAD

**Issue by geek-yang** [dianna-ai/dianna#564]
Referring to the comments in PR #554, we implement very strategic and smart masking approach based on wave functions for both images and timeseries, for instance:

for images
https://github.com/dianna-ai/dianna/blob/3f5b388ab0faa36876730a87e18f7b2876621d35/dianna/methods/rise.py#L245

for timeseries
https://github.com/dianna-ai/dianna/blob/3f97c304ad16fd4f3adce528405632a414f207b9/dianna/utils/maskers.py#L20-L22

But since the method is a bit tricky and abstract, it is not so easy to understand. Currently we don't have it documented in detail. We should add explicit documentation/docstrings/examples to explain our approach.

**Comment by cwmeijer** [comment]
I don't know yet where the explanation of the time series masking should be. I'll start typing it here for now.

Alternatives:
1. Independent random masking for each element in the cross product of channels and time steps (the most naive approach?) See #565.
2. Independent random masking for each time step
3. Independent random masking for each channel
4. A combination the above

The current approach tries to do the following:
1. Create clusters or blobs of adjecent time steps that get masked together. The rationale behind this is that time series data is often recorded on a higher resolution than the phenomena that we want to use to predict (eg. Several days of warm weather on a day resolution timeseries; multiple time steps of a certain acceleration in an accelerometer recording). In order to mask such a phenomenon from our data, we need to mask a number of adjecent timesteps.
1. We want the user to be able specify the scale of such phenomena to be masked. It is completely dataset dependent whether how many of adjecent timesteps should be masked together. In some datasets, readings on many timesteps should be considered together and therefore masked together while on other datasets no clustering should be done at all.
1. We want the specified size of the clusters or blobs to vary somewhat in order to increase the span of patterns that can be masked accurately given a large enough number of masks are used.
1. We want the probability to be masked, for each element in the cross product of channels and time steps, to be exactly equal to a user specified value.
