### ISSUE TITLE
Update the architecture  schema

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#639]
Find the schema first

**Comment by elboyran** [comment]
Starting point: https://github.com/dianna-ai/dianna-exploration/issues/103

**Comment by elboyran** [comment]
The old schema is [here](https://app.diagrams.net/#Wb!UPZtKeipi0WrFvKBlrEPP4gCzfYL1_ZNqqeyKlYhp43xuB7DeGf3QZ8Mqz5yc_MZ%2F01YA33DUP4W7ISPOFPEBBJTNI4MHVRSL4E)

**Comment by elboyran** [comment]
Can someone comment on the current drawio app schema, before committing?
Not all functions are listed, nor all arrows, the question is do we need them?

**Comment by cpranav93** [comment]
The schema looks really nice and I find it explains DIANNA in a nutshell really well! 

A couple of points:
- It might be nice to indicate compulsory inputs and optional one maybe with an "and" or "or" connection? It might make it clearer 
- A restructuring of the methods is definitely needed as we have separate ones for time-series but not for others. We should make this consistent in DIANNA and reflect it in the schema.
- Is the visualization connected to the dashboard? How does the dashboard interconnect with DIANNA?
- We could opt to categorize the utils functions differently to make the purpose clearer - i.e. maskers in utils_timeseries, tokenizer in utils_text, etc

**Comment by geek-yang** [comment]
It already looks pretty pretty nice!! I like the color scheme and the new look of diagram!

> Can someone comment on the current drawio app schema, before committing? 

Maybe instead of directly commit it to the repo, it is better to make a PR for that? Then we will not miss the changes (almost miss this issue 😂 ) and can also leave our comments there.

> Not all functions are listed, nor all arrows, the question is do we need them?

Some follow-up comments (based on @cpranav93 's input):
- We can list all methods, after splitting they will become `lime_text` `rise_image`... etc.
- In dashboard, maybe considering adding other pages/tabs to the schema, e.g. `image tab` `text tab` `timeseries tab` 
- We plan to add support for tabular data as well. So it is better to make some extra space for the incoming changes

Thanks a lot for the changes @elboyran ! The design already wins my heart ❤️

**Comment by elboyran** [comment]
Thanks for the comments, guys. Unfortunately, I'll have no time in the next 2 weeks or so to work on it. 

Would someone like to pick the issue up and address the comments and also reflect the implementations (e.g. methods splitting)?

**Comment by cwmeijer** [comment]
The schema looks very good! Great work!

In response to @geek-yang suggestion to list the whole cross product of ```[methods] x [data-domains]``` in the methods section, we could also choose to only list the methods. This would look clearer I guess, but it leaves out some details, like the fact that we don't support every data-domain with every method.

In response to Pranav's suggestion about maskers. I think putting them in utils is not ideal. I think the maskers should get a more prominent place in the package structure. Like:
```
\ methods
  \ ...
\ maskers
  \ time_series
  \ images
  \ text
\ utils
  \ ...
```

**Comment by elboyran** [comment]
[Link](https://app.diagrams.net/#Wb!UPZtKeipi0WrFvKBlrEPP4gCzfYL1_ZNqqeyKlYhp43xuB7DeGf3QZ8Mqz5yc_MZ%2F01YA33DUNHOZDA5F2365C2HPUKXVPAOSOR) updated schema
