### ISSUE TITLE
publish FRB model on zenodo

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#709]

**Comment by loostrum** [comment]
The model is now available at https://zenodo.org/records/10656614

**Comment by loostrum** [comment]
For the review of this issue, perhaps the reviewer could download the model and verify that it runs? Feeding it random float32 data of shape `[1, 32, 64, 1]` should work. It's an onnx file so the dianna tools for running models could be used.

**Comment by loostrum** [comment]
Thanks for trying it out! The issue seems to be that whatever the input data type, dianna outputs float64. The only fix is to use the `preprocess_function` to convert back to float32 (note: not float16). All onnx models accept only float32 I think, so I'm curious how it was fixed in other cases. `explain_timeseries` won't work anyway, because the data needs to be transposed. If the `runner` function works on `input_data`, I'd consider the model ok

**Comment by cwmeijer** [comment]
I tried float32 as well before trying float16. Anyway, it all makes sense and indeed the runner just works fine with the input data as long as it is casted to float32.

Everything checked and reviewed. Let's close this issue. 🥳🍹
