### ISSUE TITLE
Fix visualization functions

### ISSUE THREAD

**Issue by SarahAlidoost** [dianna-ai/dianna#713]
There are several problems related to the visualization functions:
1- The value ranges of plot, see issue #691
2- Some functions create double plots by `ax.imshow` and` plt.show()` and `return fig`
3- lack of colorbar

issues of text visualization: 
1- text visualization does not support if a word is repeated because it uses `get()` method of a dictionary to map a word to an importance value, see [here](https://github.com/dianna-ai/dianna/blob/f4736d4746e4651100139a9f6ec9ca5487c94627/dianna/visualization/text.py#L34-L40)
2- text visualization takes an argument `input_tokens` that can be optional
3- see #696 and #206 and #716

see related issues of text visualization #302, #435, #317, #285

**Comment by loostrum** [comment]
One quick comment before I forget: the `ax.imshow` is not a reason for double plots as it is a plotting command, not one that shows plots. `plt.show()` combined with returning the figure does result in double plots in notebooks because a notebook will show a figure if it's the last thing returned in a cell. This doesn't happen on the command line.
