### ISSUE TITLE
text visualizations seems to have colormap reversed 

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna#755]
See any other [RISE](https://github.com/dianna-ai/dianna/tree/main/tutorials/explainers/RISE) or some of the [LIME ](https://github.com/dianna-ai/dianna/tree/main/tutorials/explainers/RISE) tutorials images for the correct colormap convention

**Comment by elboyran** [comment]
Should be fixed in the [text tutorial](https://github.com/dianna-ai/dianna/blob/main/tutorials/explainers/LIME/lime_text.ipynb) indeed!

**Comment by elboyran** [comment]
[like]  Elena Ranguelova reacted to your message:
________________________________

**Comment by elboyran** [comment]
Also, we are now not using HTML visualization anymore, right? 
Then we should edit the 4. Visualization section of the notebook to remove that claim.

**Comment by elboyran** [comment]
@SarahAlidoost it's easy for me to fix it within my PR #769  as I just did the same for the overview notebook.

**Comment by SarahAlidoost** [comment]
> Fixed the colormap issue (though notebooks can be simplified now, by not using the colormap explicitly) with a few commits: [e0d1ee8](https://github.com/dianna-ai/dianna/commit/e0d1ee84627fa442e57e4e92d356f76091474f0b); [6e843b1](https://github.com/dianna-ai/dianna/commit/6e843b16d736a0f69f8cf80da99275624f21609d) in #769 , but found out dianna breaks if the sentence ends with a dot :-(

Thanks. Let's submit the "dot" problem in another issue. Currently, the visualization wraps the text if there are dots, see [here](https://github.com/dianna-ai/dianna/blob/b3518eced5be0a02d196dc5b477a0791281b0a90/dianna/visualization/text.py#L65). However, it has not been tested, see [here](https://github.com/dianna-ai/dianna/blob/b3518eced5be0a02d196dc5b477a0791281b0a90/tests/test_visualization.py#L84). Can you please submit the "dot" problem in a separate issue? I can try to fix it.

**Comment by elboyran** [comment]
[like]  Elena Ranguelova reacted to your message:
________________________________

**Comment by elboyran** [comment]
Fixed by commits https://github.com/dianna-ai/dianna/pull/776/commits/643b478ff8a5466982c3ff9826fb3e1ecff2d0df, https://github.com/dianna-ai/dianna/pull/776/commits/c461e7ca316008bda958ee13fa7f26ffd978d799 and https://github.com/dianna-ai/dianna/pull/776/commits/1302a4f1c651bd121f74304b5f4738ae3c41fec1.

@loostrum, @SarahAlidoost , @cwmeijer it's very strange that RISE gives always only positive scores even for negativ reviews! See RISE for text [tutorial.](https://github.com/dianna-ai/dianna/blob/overview_and_tutorials_change/tutorials/explainers/RISE/rise_text.ipynb). Any ideas?
