### ISSUE TITLE
Linting configuration changes between laptop and CI

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna#84]
As noted in the [discussion here](https://github.com/dianna-ai/dianna/commit/5684ac0d7ad6d594d6daece0cb24b0f1ea39a7ed), it seems that on local machines both linting (prospector) and isort yield different results than on CI. Specifically, CI runs seem to be more lenient than local runs, which means CI misses issues. We should find out why this happens and how to fix it.

**Comment by cwmeijer** [comment]
I think the main problem was that we didn't understand what the CI was actually doing.
Our expectations where incorrect because wed didn't know how the CI runs on a branch after merging it with main. Now we do.
If we find still find discrepancies that we don't understand between linting on the server and locally, we should make note of it and reopen this issue.

**Comment by egpbos** [comment]
Agreed.

**Comment by egpbos** [comment]
@loostrum and I, while working on #188, run into this again. We tried branching off main locally and merging the PR branch into that, running prospector on it, which should be then the same as what CI runs on. Unfortunately, locally we get no prospector issues, while in CI we do. So it's back!

**Comment by egpbos** [comment]
Perhaps it was not a problem after all. It could have just been an import issue due to improper setup.cfg which didn't detect namespace modules...

**Comment by egpbos** [comment]
Yup that was it.
